### ISSUE TITLE
Crashing: No module named 'pipes'

### ISSUE THREAD

**Issue by guerilla7** [cnunescoelho/kiroku#6]
(venv) ron@Rons-MBP-14 kiroku % ./kiroku
Traceback (most recent call last):
  File "/Users/ron/kiroku/./kiroku", line 7, in <module>
    from fire import Fire
  File "/Users/ron/kiroku/venv/lib/python3.13/site-packages/fire/__init__.py", line 21, in <module>
    from fire.core import Fire
  File "/Users/ron/kiroku/venv/lib/python3.13/site-packages/fire/core.py", line 59, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'

**Comment by cnunescoelho** [comment]
Can you send me information about the environment? linux, windows, mac (which processor?), browser

**Comment by cnunescoelho** [comment]
and of course, which python environment and version

**Comment by guerilla7** [comment]
@cnunescoelho 

Hardware: Apple M1 Pro
OS: Sequoia 15.1
Python 3.13.0
Browser: Version 130.0.6723.117 (Official Build) (arm64)

**Comment by cnunescoelho** [comment]
I am removing Fire in the next commit. It should work.
